# Generated by Django 2.0.2 on 2018-02-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Рабочее'), ('INACTIVE', 'Нерабочее')], default='ACTIVE', max_length=10)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('serial_number', models.CharField(max_length=200, verbose_name='Серийный номер')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Employee', verbose_name='Пользователь')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Model', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(default='Беларусь', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transfer', models.DateField(verbose_name='Дата перемещения')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='Минск', max_length=200)),
                ('country', models.CharField(default='Беларусь', max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Service'),
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyAddress'),
        ),
        migrations.AddField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Entity'),
        ),
    ]
